In [1]:
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
# Criação da matriz com os dados e executando o teste

novela = np.array([[19,6], [43, 34]])
novela

array([[19,  6],
       [43, 34]])

In [3]:
#segundo valor é o pvalue
#valor de p é maior que 0,05 não há evidencias de diferença signinificativa na hipótese nula
chi2_contingency(novela)
#função que calcula o Qui - Quadrado :chi2_contingency

(2.4264847088395487,
 0.11930016177496153,
 1,
 array([[15.19607843,  9.80392157],
        [46.80392157, 30.19607843]]))

In [4]:
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [5]:
chi2_contingency(novela2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))